version: 2.0
jobs:
  build:
    docker:
      - image: cimg/python:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Run python script
      - run: pip install PyGithub --user
      - run: python main.py
      - run: git version
      - run: git status
      - run: git config --global user.email $GITHUB_MAIL
      - run: git config --global user.name $GITHUB_USER
      - run: git checkout main
      - run: git pull origin main
      - run: git add .
      - run: git commit -m "Update From Circle CI"
      - run: git push origin
      - run: echo 'done'
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: main

    jobs:
      - build
