version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Run python script
      - run: pip install PyGithub --user
      - run: python3 main.py
      - run: git version
      - run: git status
      - run: git config --global user.email "1245244711@qq.com"
      - run: git config --global user.name "xuya227939"
      - run: git checkout main
      - run: git pull origin main
      - run: git add .
      - run: git commit -m "Update From Circle CI"
      - run: git push https://$GITHUB_LOGIN:$GITHUB_PASSWORD@github.com/$GITHUB_LOGIN/blog.git
      - run: echo 'done'
